version: '3'

services:
  word-information-collector:
    build: .
    container_name: word-information-collector
    depends_on:
      - word-mongodb
    command: ["/usr/local/app/run.sh"]
    networks:
      web:
    ports:
      - 8080:8080
    environment:
      TZ: "America/Sao_Paulo"
      SERVER_PORT: "8080"

  word-mongodb:
    image: mongo:3.6.3
    container_name: word-mongodb
    command: --bind_ip_all
    networks:
      web:
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: words
    volumes:
      - ./database/init_words.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb:/data/db

  word-mongo-express:
    image: mongo-express
    container_name: word-mongodb-express
    restart: always
    depends_on:
      - word-mongodb
    networks:
      web:
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: word-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234


networks:
  web:

volumes:
  mongodb:
    driver: local


